import "package:flutter/widgets.dart";
import "icon_data.dart";

// THIS FILE IS AUTOMATICALLY GENERATED!

class IcoMoonIcons {
    static const IconData arrow_left_right = const IcoMoonIconData(0xe900);
    static const IconData arrow_left = const IcoMoonIconData(0xe901);
    static const IconData arrow_right = const IcoMoonIconData(0xe902);
    static const IconData bullseye = const IcoMoonIconData(0xe903);
    static const IconData chevron_down = const IcoMoonIconData(0xe904);
    static const IconData chevron_left = const IcoMoonIconData(0xe905);
    static const IconData chevron_right = const IcoMoonIconData(0xe906);
    static const IconData chevron_up = const IcoMoonIconData(0xe907);
    static const IconData clipboard = const IcoMoonIconData(0xe908);
    static const IconData crop = const IcoMoonIconData(0xe909);
    static const IconData gear_fill = const IcoMoonIconData(0xe90a);
    static const IconData heart_fill = const IcoMoonIconData(0xe90b);
    static const IconData heart = const IcoMoonIconData(0xe90c);
    static const IconData image = const IcoMoonIconData(0xe90d);
    static const IconData mic_fill = const IcoMoonIconData(0xe90e);
    static const IconData mic = const IcoMoonIconData(0xe90f);
    static const IconData pin_fill = const IcoMoonIconData(0xe910);
    static const IconData pin = const IcoMoonIconData(0xe911);
    static const IconData volume_down = const IcoMoonIconData(0xe912);
    static const IconData volume_off = const IcoMoonIconData(0xe913);
    static const IconData volume_up = const IcoMoonIconData(0xe914);
    static const IconData x = const IcoMoonIconData(0xe915);
}
